### PR TITLE
Add python 3.6.6 and 3.7.0 to travis

### PR DESCRIPTION
**Pull request by marcelobelli**
Update Travis to test the lib using python 3.6.6 and 3.7.0

### CODE REVIEW

**Comment by lamenezes** [comment]
@marcelobelli thanks for your PR! I suggest also adding `py37` to `tox.ini` file [1]

[1] https://github.com/olist/correios/blob/master/tox.ini

**Comment by jpbonson** [comment]
@marcelobelli do you still intend to continue this PR? otherwise, do you mind if I close it? I noticed it is not being worked on anymore

**Comment by marcelobelli** [comment]
@jpbonson, I totally forgot! 😱 

Yes, I will continue this PR!

**Comment by gfabricio** [comment]
@marcelobelli any update about this pr?

**Comment by marcelobelli** [comment]
Hi @gfabricio, I will finish this PR today

**Comment by jpbonson** [comment]
@marcelobelli there is no need to hurry to finish it. We could close it, so it would stop showing up in the list of PRs, you work on it again in its branch, and then you can open another PR. What do you think? :slightly_smiling_face:

**Comment by marcelobelli** [comment]
I think that's better @jpbonson :smile:

**Pull request closed without merging**
