### PR TITLE
Created skeleton to correios docs

### PR DESCRIPTION
**Pull request by robertoduessmann**
Created skeleton to correios docs.

First pull request of some to organize new documentation.

refs https://github.com/olist/correios/issues/100

### CODE REVIEW

**Comment by osantana** [comment]
Isn't a better idea to use sphinx to allow us to publish documentation at readthedocs.org?

And, please, don't use docstrings in code, ok? I don't like to mix code and documentation at the same place.

**Comment by robertoduessmann** [comment]
Thanks for feedback @osantana .

I searched about sphinx and it's a good option.

I created the initial sphinx config files. Can you see again?

**Comment by osantana** [comment]
Looks good! Can you, please, update branch to include a build fix that I added to the master?

**Comment by robertoduessmann** [comment]
Nice, now the build is ok :)

**Pull request merged**
