### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Comment by osantana** [comment]
Why you put builder in models package but not the serializer?

**Comment by jairhenrique** [comment]
> Why you put builder in models package but not the serializer?

For me, serializer and model are distinct things. Model has the code logic and serializer only represents that. It makes no sense for me to be together.

**Comment by osantana** [comment]
> For me, serializer and model are distinct things. Model has the code logic and serializer only represents that. It makes no sense for me to be together.

I agree. So lets push this a little...

Add a new `PostingList.serialize(serializer)` method https://github.com/olist/correios/blob/master/correios/models/posting.py#L684:

```python
def serialize(serializer_class: PostingListSerializer):
   serializer = serializer_class(self)
   serializer.validate()
   return serializer.get_result()
```

... then we refactor the current serializer code and clients do make it work correctly...

What you think?

**Comment by lamenezes** [comment]
> ... then we refactor the current serializer code and clients do make it work correctly...
>
> What do you think?

IMHO it seems weird the serialization being done by the model and by using type hints it makes look like the model is tied to the `PostingListSerializer`.

But I think it would be good to have the serializer related to the model and have:
```python
serializer = Serializer(model)
serializer.validate()
serializer.get_xml()
```

instead of

```python
serializer = Serializer()
document = serializer.get_document()
serializer.validate(document)
serializer.get_xml(document)
```

**Comment by osantana** [comment]
> IMHO it seems weird the serialization being done by the model and by using type hints it makes look like the model is tied to the PostingListSerializer.

The Model.serialize(serializer) is a helper method. Helper methods exists to make life easier in the best style of Zen of Python "Although practicality beats purity". The responsability for serialization still relies on the Serializer class.

On the other half of your comment you suggest

```
serializer = Serializer(model)
serializer.validate()
serializer.get_xml()
```

This construction is "ok" if your serializer exists to serializes only one model. Example:

```python
result = []
for posting_list in posting_lists:
    serializer = Serializer(posting_list)  # creates a serializer exclusively for this posting_list
    serializer.validate()
    result.append(serializer.get_xml())
```

Now using the idea that a Serializer 'serializes things'

```python
result = []
serializer = Serializer()
for posting_list in posting_lists:
    serializer.validate(posting_list)
    result.append(serializer.get_xml(posting_list))
```

You can also extend and customize Serializer

```
r = []
serializer = Serializer(codec="iso-8859-1")  # serialize objects using iso-8859-1 codec
for obj in objects:
    serializer.validate(obj)
    r.append(serializer.get_xml(obj))
```

The main issue, at the end, is the `.validate(obj)` method in Serializer class that ends up with two responsabilities: validate && serialize objects. Could we include a deeper refactoring and move .validate() method into model class?

**Comment by lamenezes** [comment]
> The Model.serialize(serializer) is a helper method. Helper methods exists to make life easier in the best style of Zen of Python "Although practicality beats purity". The responsability for serialization still relies on the Serializer class.

Then I would think a helper function would work better:

```python
def serialize(model: Model, serializer_class: Serializer):
    serializer = serializer_class(model)
    ...
```

This way we don't tie the helper function to a specific model or serializer and it's still easy to use.

> This construction is "ok" if your serializer exists to serializes only one model. Example:

I don't see any problem in doing things this way when performing serialization on a list of models...

> You can also extend and customize Serializer

It's also possible to extend and customize Serializer the other way

> The main issue, at the end, is the .validate(obj) method in Serializer class that ends up with two responsabilities: validate && serialize objects. Could we include a deeper refactoring and move .validate() method into model class?

Model validation and serialization validation are different. I think it does make sense to validate stuff on the model, but we can't just move serializer validation (that involves the loading of a xsd file etc.) to the model.

**Comment by osantana** [comment]
> This way we don't tie the helper function to a specific model or serializer and it's still easy to use. But it requires the creation of the Model and Serializer base classes which I think makes sense if we're planning a bigger refactor.

Ok. This is a question of style. I don't like to use functions in an OO software.

> I don't see any problem in doing things this way when performing serialization on a list of models...

I see. A lot. Why we need to instantiate one serializer for each model to discard it after serialization (refcount/GC costs memory and CPU)?

> It's also possible to extend and customize Serializer the other way

Not in all directions. I can extend Serializer to extend more than one model, eg:

```python

class XMLSerializer(Serializer):
    def __init__(self, charset="utf-8"):
        self.charset = charset

    def _get_xml_from_dom(self, dom):
        ...

    def serialize_posting_list(self, posting_list):
        for sl in posting_list.shipping_labels:
            ... = self.serialize_shipping_label(sl)
       return self._get_xml_from_dom(self, dom)

    def serialize_shipping_label(self, shipping_label):
        ...
```

In other way I'd have to implement one serializer for each model duplicating the code *or* creating a complex hierarchy of classes.

Besides that you will pay the price in usability *and* creates an artificial coupling between model and serializer:

```python
class Serializer:
    def __init__(self, model, charset='utf-8'):  # we've data arguments *and* config arguments conflicting
        self.model = model  # now serializers has a model dependency
```

> Model validation and serialization validation are different. I think it does make sense to validate stuff on the model, but we can't just move serializer validation (that involves the loading of a xsd file etc.) to the model.

So we need to ".validate()" the xsd internally in serializer but assure that the model is correct enough to guarante that serializer will never generate an invalid XML.

**Comment by osantana** [comment]
I'm closing this PR but I'm applying some parts of it on #109

**Pull request closed without merging**
