### PR TITLE
[proposal] use codecov instead of coveralls

### PR DESCRIPTION
**Pull request by jairhenrique**

### CODE REVIEW

**Comment by adlermedrado** [comment]
Hello @jairhenrique, thank you for this PR.

I have a question: Is there any significant advantage in this change?

Thanks.

**Comment by jairhenrique** [comment]
@adlermedrado 🤔 

`codecov` has a better report than `coveralls`. How many people see the coveralls site? This [report](https://github.com/olist/correios/pull/92#issuecomment-325521528)  is awesome and the `codecov` site is better!

**Comment by adlermedrado** [comment]
@jairhenrique Nice. 
It's OK for me. Let's wait and see what the rest of the team thinks about it.
:+1:

**Comment by osantana** [comment]
> How many people see the coveralls site?

:raising_hand_man: 

But I'm ok with this change. :smile:

**Pull request merged**
